version: "3.0"

services:
  betclic-homework:
    container_name: betclic-homework
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=local
    volumes:
      - './src:/usr/src/app/src'
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 4200:4200
      - 49153:49153
      - 81:80
    networks:
      - betclic-homework-network

networks:
  betclic-homework-network:
    external: true
